# This is a basic workflow to allow you to automate your PowerShell code!

name: Azure Tag Check

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *' #Lookup cron numberes
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-tags: 
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: Install Azure CLI
      uses: azure/login@v1
      
    - name: Install Az PowerShell module
      run: Install-Module -Name Az -Force
      
    - name: Run PowerShell script
      shell: pwsh
      run: | #inject script here
