# This is a basic workflow to allow you to automate your PowerShell code!

name: Azure Tag Check

on:
  on:
    push:
      branches: [ main ]
    pull_request:
      # The branches below must be a subset of the branches above
      branches: [ main ]
    schedule:
      - cron: '0 0 * * *'  # Run the script every day at midnight UTC
    
jobs:
  get_last_used_date:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup PowerShell
      uses: microsoft/setup-powershell@v1
      
    - name: Login to Azure
      id: login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Execute script
      shell: pwsh
      run: |
        ./${{ github.event.repository.name }}/GetAzResourceTags_AE.ps1

