# This is a basic workflow to allow you to automate your PowerShell code!

name: Azure Tag Check

on: 
  workflow_dispatch:
  
#  schedule:
#      - cron: '0 0 * * *'  # Run the script every day at midnight UTC
    
jobs:
  get-last-used-date:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@v3
    
    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: Execute script
      shell: pwsh
      run: |
        ./${{ github.event.repository.name }}/GetAzResourceTags_AE.ps1



    
